# TeamSync v20200702
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 4
:sectnums:
:toc:
:toclevels: 4
:toc-title:
29 april 2020 Paul Wiegmans <p.wiegmans@svok.nl>

TeamSync is een PowerShell-script dat gegevens ophaalt uit Magister en overbrengt naar School Data Sync ten behoeve van een geautomatiseerde aanmaak van Teams in een Microsoft 365 omgeving. 

Deze oplossing maakt gebruik van https://sds.microsoft.com/[Microsoft School Data Sync]. 

Inspiratie hiervoor komt uit eerder werk genaamd 'v06-sds-files_FONSVITAE.ps1' door Wim den Ronde, Eric Redegeld, Joppe van Daalen.

Gebruikt jouw school Somtoday en zoek je een koppeling tussen Somtoday en School Data Sync ? Bezoek dan https://github.com/DwayneSelsig/Somtoday2MicrosoftSchoolDataSync[DwayneSelsig/Somtoday2MicrosoftSchoolDataSync]

toc::[]

## Werking 

TeamSync is gesplitst in twee scripts: 

* `Ophalen-MagisterData.ps1`
* `Transformeren-Naar-SchoolDataSync.ps1`

Deze twee scripts kunnen achter elkaar worden uitgevoerd. 
Voor het ophalen van gegevens wordt gebruik gemaakt van een SOAP/XML webservice die toegang biedt tot de Magisteromgeving van een school. Uitvoer bestaat uit 6 CSV-bestanden die nodig zijn voor het synchroniseren met een synchronisatieprofiel in School Data Sync.

De werking is als volgt:

Script 1 `Ophalen-MagisterData.ps1` verzorgt ophalen van gegevens: 

* leest variabelen uit Ini-bestand
* leest filters
* haalt session token op
* haalt gegevens van leerling op
* haalt gegevens van docenten op
* genereert lijst met vakken
* bewaart tussenresultaten in bestand

Script 2 `Transformeren-Naar-SchoolDataSync.ps1` verzorgt het transformeren en uitvoeren:

* leest variabelen uit Ini-bestand
* leest filters
* leest tussenresultaten uit bestand
* past filters toe
* genereert een lijst met actieve teams
* schrijft SDS-bestanden naar datauitvoermap. 

## Bestanden en mappen
Bestanden en mappen worden verwacht in dezelfde map als het script. 

### Ini-bestand
bij verstek "teamsync.ini"; dit bestand bevat instellingen voor het TeamSync-script, zoals de gebruikersnaam, wachtwoord en URL voor het aanspreken van de webservice, de schoolnaam, het BRINnummer en een teamnaam-prefix. Een alternatief ini-bestandsnaam wordt opgegeven op de commandoregel via de parameter `-Inibestandsnaam`.

### Datainvoermap
In deze map worden filters geplaatst. Zie Invoerfilter.

### Datakladmap
In de datakladmap worden tussenbestanden opgeslagen. en kan worden gebruikt om de goede werking te controleren van de Magister webservice.
Het script `Ophalen-Magisterdata.ps1` bewaart hier de tussentijdse bestanden met leerling- en docent- en vakkengegevens in CliXML-formaat. Het script `Transformeren-Naar-SchoolDataSync.ps1` leest deze bestanden in voor verdere verwerking. U zult hier tegenkomen:

* `mag_leer.clixml`
* `mag_docent.clixml`
* `mag_vak.clixml`
* `personeelemail.clixml`
* `teamlid.csv`

### Datauitvoermap

De uitvoer worden opgeslagen in de datauitvoermap. Het script maakt volgens de specificaties van SDS de volgende bestanden aan. 

* `School.csv`
* `Section.csv`
* `Student.csv`
* `StudentEnrollment.csv`
* `Teacher.csv`
* `TeacherRoster.csv`

### Filters

In de datainvoermap kunnen één of meer filters worden geplaatst, dis de hoeveelheid te verwerken gegevens reduceren. Er zijn een aantal filters te definieren , die zowel in `Ophalen-MagisterData.ps1` als `Transformeren-Naar-SchoolDataSync.ps1` wordt gebruikt. De volgende filters kunnen worden gedefinieerd door het overeenkomstige bestand in de datainvoermap te definieren. 

* `excl_docent.csv` : dit bevat filters voor het uitsluiten van docenten op docentcode.
* `incl_docent.csv` : dit bevat filters voor het insluiten van docenten op docentcode.
* `excl_klas.csv` : dit bevat filters voor het uitsluiten van leerlingen op klasnaam.
* `incl_klas.csv` : dit bevat filters voor het insluiten van leerlingen op klasnaam.
* `excl_studie.csv` : dit bevat filters voor het uitsluiten van leerlingen op studie.
* `incl_studie.csv` : dit bevat filters voor het insluiten van leerlingen op studie.
* `incl_locatie.csv` : dit bevat filters voor het insluiten van leerlingen op locatie.

Deze bestanden bevatten filters, die selectief records uit de invoer filteren. Ze kunnen **exclusief** of uitsluitend filteren, dat wil zeggen dat overeenkomende records worden weggegooid en uitgesloten van verwerking, of ze kunnen **inclusief** of insluitend filteren, dat wil zeggen dat alleen de overeenkomende records verder worden verwerkt.

Het gebruik van deze filterbestanden is optioneel. Als ze bestaan, worden ze ingelezen en gebruikt. Als ze niet bestaan, wordt er niet gefilterd. Indien gebruikt, dan kan elk van deze bestand een of meer filters bevatten, elk op een eigen regel, die worden toegepast met behulp van de match-operator voor het filteren van de leerlingen of docenten. Elke filter match een deel van de invoer. Wildcards zijn niet nodig. Alle tekens met een speciale betekenis voor de match-operator zijn hierbij toegelaten. Plaats geen lege regels in het filterbestand.

Speciale betekenis hebben:

* `^` matcht het begin van een zoekterm 
* `$` matcht het eind van een zoekterm

#### Voorbeelden van filters

Voorbeeld : We willen de VAVO-leerlingen niet verwerken; alle studies die eindigen op VAVO moeten worden uitgesloten.

Het bestand data_in\excl_studie.csv wordt aangemaakt en bevat: 
```
VAVO$
```

Voorbeeld : We willen de leerlingen van Mavo, Havo, Vwo en de brugklassen verwerken; alle leerlingen in een studie die begint met B,M,H of V moeten worden verwerkt. 

Het bestand data_in\incl_studie.csv wordt aangemaakt en bevat:
```
^M
^H
^V
^B
```

Voorbeeld : we willen alleen 4 en 5 Havo en verwerken; alle leerlingen in de klas die begint met '4H' of '5H' moeten worden verwerkt. 

Het bestand data_in\incl_klas.csv wordt aangemaakt en bevat:
```
^5H
^4H
```

## Ini-parameters

Het INI-bestand definieert een aantal parameters, die nodig zijn voor o.a. het authenticeren van de toegang tot de Magister SOAP webserver. Het Ini-bestand heet bij verstek 'teamsync.ini' in de map van het script, maar een ander INI-bestand kan worden gebruik indien op de commandoregel de parameter -Inifile <bestandsnaam> wordt gespecificeerd. 

De parameters in het INI-bestand worden gespecificeerd als een naam-waarde-paar en hebben de volgende vorm:

```
<naam>=<waarde>
```

Aanhalingstekens zijn toegestaan maar niet nodig. Spaties in het waarde-deel zijn toegestaan. 

Indien een bestandsnaam of mapnaam met meer dan één niveau wordt gespecificeerd, gebruik dan dubbele backslashes, bijvoorbeeld `datainvoermap=Submap1\\Submap2\\Submap3`

De volgende parameters moeten een waarde hebben:

[square]
* `brin=waarde` : BRIN-nummer van de school
* `schoolnaam=waarde` : naam van de school in SDS
* `magisterUser=waarde` : webservice-gebruikersnaam
* `magisterPassword=waarde` : webservice-wachtwoord
* `magisterUrl=waarde` : webservice-URL
* `teamnaam_prefix=waarde` : unieke prefix voor teams in SDS
* `maakklassenteams=waarde` : schakelaar voor aanmaken van een team voor iedere (stam)klas
* `datainvoermap=waarde` : pad naar invoermap relatief t.o.v. scriptpad
* `datakladmap=waarde` : pad naar kladmap relatief t.o.v. scriptpad
* `datauitvoermap=waarde` : pad naar uitvoermap relatief t.o.v. scriptpad
* `useemail=waarde` : schakelaar : indien '1' gebruik email als unieke id i.p.v. Login
* `ADsearchbase=waarde` : OU waarin wordt gezocht om userPrincipalName van personeel te lezen
* `ADserver=waarde` : servernaam om userPrincipalName van personeel te lezen

#### Brin
Dit is het BRIN-nummer van de school. Vraag je schooladminstratie of directie hiervoor.

#### Schoolnaam 
Dit is de schoolnaam zoals die in SDS moet zijn gedefinieerd. Verder niet heel belangrijk.

#### MagisterUser, MagisterPassword, MagisterUrl 
Deze gegevens zijn vereist om toegang te krijgen tot de Medius Webservices. De LAS-beheerder maakt een gebruiker aan in de Webservice gebruikerslijst in Magister. De gebruikersnaam en wachtwoord moeten worden gegeven in `MagisterUser` en `MagisterPassword`. Deze gebruiker heeft toegangsrechten nodig tot de *_ADfuncties_* in de Medius Webservices. De MagisterUrl is de URL waar de webservices worden aangeboden. Dit bestaat uit de schoolspecifieke URL voor  Schoolwerkplek met daarachter poort en padaanduiding _:8800/doc_ . De hele URL ziet er uit als `https://schooldomein.swp.nl:8800/doc`.

#### Teamnaam_prefix
Deze naam wordt als prefix voor de naam van elk aan te maken team geplakt. Je kunt dit gebruiken om aan te duiden voor welke teams exclusief door School Data Sync actief gesynchroniseerd worden en voor welke school of welk jaar deze teams actief zijn. Een nuttige prefix is bijvoorbeeld "JPT 1920". Spaties in de naam worden omgezet in underscores ten behoeve van het bepalen van de ObjectID.

#### Datainvoermap
Dit specifieert de naam van de datainvoermap, relatief ten opzichte van de locatie van het script. Bij verstek is de naam van de datainvoermap `data_in`. 

#### Datakladmap
Dit specificeert de mapnaam van de datakladmap relatief ten opzichte van de locatie van het script. Bij verstek is de datakladmap `data_temp`.

#### Datauitvoermap
Dit specificeert de mapnaam van de datauitvoermap relatief ten opzichte van de locatie van het script. Bij verstek is de datauitvoermap `data_uit`.

#### useemail
Wanneer deze waarde "0" is , worden medewerkers en leerling uniek aangeduid met attribuut "login" in Magister. 
Wanneer deze waarde "1" is , worden medewerkers en leerling uniek aangeduid met het attribuut "userPrincipalName" van usersobjecten in Active Directory. De UserPrincipalName wordt achterhaald door te zoeken in AD naar een user wiens attribuut "EmployeeID" gelijk is aan het Magister veld "stamnr_str". Vervolgens wordt het userPrincipalName gebruikt als unieke identifier voor de medewerkers in de uitvoer voor School Data Sync. Docenten waarvan het email niet kan worden opgezocht op deze manier in de Active Directory worden eruit gefilterd en verschijnen niet in de uitvoer
De leerlingen worden uniek geidentificeerd met het "email" veld in de Magister leerlingkaart. Het is de verantwoordelijkheid van de school om ervoor te zorgen dat het email-veld van leerlingen is ingevuld met de overeenkomstige userPrincipalName van de leerling in Azure AD / Microsoft 365. 

#### ADsearchscope
Deze parameter is verplicht wanneer "useemail=1". De waarde duidt de OU waarin medewerkers worden gelezen voor het bepalen van userPrincipalName.

#### ADserver 
Deze parameter is verplicht wanneer "useemail=1". De waarde bevat de servernaam waarin medewerkers worden gelezen voor het bepalen van userPrincipalName. 

## Commandoregel

### Inibestandsnaam Parameter
Met de commandoregelparameter -Inibestandsnaam wordt de bestandsnaam van een alternatief Ini-bestand opgegeven, relatief ten opzichte van de map waarin het script staat. Deze voorziening maakt het mogelijk om gegevens van verscheidene instanties van magister gescheiden te verwerken. Bij verstek is de Inibestandsnaam `teamsync.ini`. 

Een voorbeeld : 

 <scriptnaam> -Inibestandsnaam <inibestandsnaam> 

waarbij `<inibestandsnaam>` de naam aanduidt van een alternatief ini-bestand. 

#### Voorbeeld
Met het volgende CMD commandoscript kan het ini-bestand 'Team-JPT.ini' worden gebruikt om script 1 en 2 uit te voeren, wanneer deze in dezelfde map als dit commandoscript staan. 

```
@echo off
Powershell.exe -NoProfile -NoLogo -ExecutionPolicy Bypass -File "%~dp0Ophalen-MagisterData.ps1" -Inibestandsnaam "Team-JPT.ini"
Powershell.exe -NoProfile -NoLogo -ExecutionPolicy Bypass -File "%~dp0Transformeren-Naar-SchoolDataSync.ps1" -Inibestandsnaam "Team-JPT.ini"
```

## Tips en trucs

### Wat als het script op zijn bek gaat?

De twee scripts loggen alle schermuitvoer in een zogenaamd "transcript" en bewaren dit in een bestand, met de naam van het scripts, en met extensie ".log". Kijk in deze logs voor informatie over foutmeldingen die het script geeft in onvoorziene omstandigheden, en op welke regel in het script dit gebeurde.

### Controle van uitvoer

In de datakladmap produceert `Transformeren-naar-SchoolDataSync` een aantal voor mensen leesbare bestanden, die inzicht geven in welke teams door School Data Sync aangemaakt zouden worden en welke gegevens worden verwerkt. 

Script `Ophalen` genereert: 

* `leerling.csv` : CSV-bestand (comma separated value formaat, in te lezen in Excel) met platte leerlinglijst uit Magister
* `docent.csv` : CSV-bestand met platte medewerkerlijst uit Magister

Script `Transformeren` genereert:
* `teamactief.csv` : CSV-bestand met actieve teams die door SDS worden aangemaakt: teamid, teamnaam, docentaanta, docentnamen, leerlingaantal, leerlingnamen.
* `team0doc.csv` : CSV-bestand met teams met uitsluitend leerlingen, en die het niet gehaald hebben naar SDS.
* `team0ll.csv` : CSV-bestand met teams met uitsluitend docenten, en die het niet gehaald hebben naar SDS.

### Typische gebruikscenarios

#### Testen

Gedurende het testen is het meest  handig als `Ophalen-MagisterData.ps1` gedurende een run zonder filters wordt uitgevoerd om alle gegevens op te halen uit Magister. Wanneer dit eenmaal is gebeurd, dan kan `Transformeren-naar-SchoolDataSync.ps1` herhaaldelijk met één of meer filters worden uitgevoerd om te kijken wat het resultaat zou worden. Dit laatste script wordt veel sneller uitgevoerd, omdat het niet steeds opnieuw de gegevens uit Magister hoeft op te halen. 

#### Een Magister, twee scholen 

Een scenario van het soort 'Een Magister - twee scholen' kan er zo uitzien: 

* Het script 'Ophalen-MagisterData.ps1' wordt uitgevoerd met een aangepast ini-bestand, zonder filters, dat alle gegevens worden opgehaald uit Magister. Dit levert snelheidswinst op. De tussenresultaten worden opgeslagen in een algemene datakladmap.

* De tussenresultaten `mag_leer.clixml`, `mag_doc.clixml` `mag_vak.clixml` en eventueel `personeelemail.clixml` worden gekopieerd van de algemene datakladmap naar een school-specifieke datakladmap.
* Het script `Transformeren-naar-SchoolDataSync.ps1` wordt één keer uitgevoerd voor elke school met een vschool-specifiek ini-bestand: 
** datainvoermap, datakladmap en datauitvoermap verwijzen naar een school-specifieke map 
** de schoolspecifieke datainvoermap bevat school-specifieke filters, bijvoorbeeld voor locatie. 
** `teamprefix` verschilt per school.

Door de schoolspecifieke filters worden alleen de leerlingen verwerkt die voor een school interessant zijn. Dit verhoogt de verwerkingssnelheid. 

Dit scenario wordt compleet met een synchronisatieprofiel voor elke school in School Data Sync. De uitvoerbestanden worden geupload naar het respectievelijke synchronisatieprofiel.

## Handige links


* https://sds.microsoft.com/[Microsoft School Data Sync]
* https://github.com/DwayneSelsig/Somtoday2MicrosoftSchoolDataSync[DwayneSelsig/Somtoday2MicrosoftSchoolDataSync]
