= TeamSync versie 20210708
Paul Wiegmans <p.wiegmans@svok.nl>
8 juli 2021 

:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 4
:sectnums:
:toc:
:toclevels: 4
:toc-title:

TeamSync is een PowerShell-script dat gegevens ophaalt uit Magister en overbrengt naar School Data Sync ten behoeve van een geautomatiseerde aanmaak van Teams in een Microsoft 365 omgeving. 

Deze oplossing maakt gebruik van https://sds.microsoft.com/[Microsoft School Data Sync]. 

Inspiratie hiervoor komt uit eerder werk genaamd 'v06-sds-files_FONSVITAE.ps1' door Wim den Ronde, Eric Redegeld, Joppe van Daalen.

Gebruikt jouw school Somtoday en zoek je een koppeling tussen Somtoday en School Data Sync ? Bezoek dan https://github.com/DwayneSelsig/Somtoday2MicrosoftSchoolDataSync[GitHub: DwayneSelsig/Somtoday2MicrosoftSchoolDataSync]

toc::[]

== Installatie

. Download link:Import-Magister.ps1[Import-Magister.ps1], link:Export-SchoolDataSync.ps1[Export-SchoolDataSync.ps1] 
en link:Teamsync.cmd[Teamsync.cmd]  en plaats deze in een map naar keuze
. Creeer een bestand `Teamsync.ini` in dezelfde map naar het voorbeeld   link:Teamsync-Voorbeeld.ini[Teamsync-Voorbeeld.ini] en pas de parameters aan je eigen behoefte aan.
. Start Teamsync met het commando link:Teamsync.cmd[Teamsync.cmd].

== Werking 

TeamSync leest uit Magister lijsten met leerlingen, docenten, klassen, lesgroepen en vakken.,
TeamSync genereert hieruit lijsten waarin voor elk samenwerkingsverband bestaande uit lesgroep of combinatie van klas en vak, waarvan zowel leerlingen als docent(en) lid zijn,  een actief team in de uitvoer terechtkomt. Deze lijsten vormen de basis voor een actieve synchronisatie van https://sds.microsoft.com/[Microsoft School Data Sync], die de juiste Microsoft 365 Teams aanmaakt, maakt de juiste docent teameigenaar en voegt de juiste leerlingen als leden toe.

TeamSync bestaat uit twee scripts: 

* `Import-Magister.ps1`
* `Export-SchoolDataSync.ps1`

Script `Import-Magister.ps1` wordt eerst uitgevoerd om gegevens uit Magister op te halen. Daarna wordt script `Export-SchoolDataSync.ps1` uitgevoerd om de bestanden te genereren ten behoeve van https://sds.microsoft.com/[Microsoft School Data Sync]. De uitvoer bestaat uit 6 CSV-bestanden die nodig zijn voor synchronisatie met een profiel in https://sds.microsoft.com/[Microsoft School Data Sync].

Voor het ophalen van gegevens wordt gebruik gemaakt van de https://sikkepitje.nl/Tech/MagisterSOAP2020[Magister SOAP/XML webservice]. Hiervoor is een geldige gebruikersnaam en een wachtwoord vereist met permissies voor het uitvoeren van webqueries. Er wordt gebruik gemaakt van de standaard Web API van Magister. Er zijn geen zogenaamde aangepaste lijsten of 'custom queries' nodig. 

=== Identiteiten koppelen

Voor het genereren van de juiste gegevens voor School Data Sync moeten de identiteiten van docenten en leerlingen in Magister worden gepaard (gekoppeld, "match") aan de overeenkomstige identiteiten van alle gebruikers in Microsoft 365 en Teams, dus in Azure Active Directory (AAD). In de uitvoer die TeamSync genereert, wijst ID naar de unieke identiteit van een medewerker of gebruiker in AAD. De ID kan een suffix bevatten, maar dat hoeft niet. Indien nodig wordt door School Data Sync aan dit veld de suffix toegevoegd om te refereren aan een unieke gebruiker in AAD. 

Voor leerlingen kan makkelijker het Magister email gebruikt om de unieke ID te bepalen. Voor medewerkers is dit lastiger omdat in Magister geen e-mailadres is opgeslagen op een manier die TeamSync kan uitlezen. 

IMPORTANT: Hier wordt ervan uitgegaan dat alle gebruikersaccounts al in AAD aanwezig zijn en dus niet door School Data Sync actief worden aangemaakt.

De volgende methoden van koppeling worden ondersteund voor medewerkers:

* ID <- Magister:code
* ID <- Magister:loginaccount
* ID <- CSV[Magister:stamnr]

De volgende methoden van koppeling worden ondersteund voor leerlingen:

* ID <- Magister:email
* ID <- Magister:loginaccount

In het configuratiebestand moet één koppelmethode voor leerlingen en één koppelmethode voor medewerkers worden gedefinieerd. 

IMPORTANT: TeamSync vanaf versie 20201127 ondersteunt niet meer het opzoeken van de UserPrincipalName in active Directory (via INI-parameters `useemail`, `ADsearchscope`, `ADserver`). Het alternatief hiervoor is om een CSV-opzoektabel te gebruiken. Je kunt deze CSV-tabel aanmaken met behulp van een script die de informatie leest uit Active Directory of uit een andere bron. Een voorbeeld van een script die de CSV-tabel vult met informatie uit Active Directory vind je in link:Ophalen-ADMedewerkerUPN.ps1[Ophalen-ADMedewerkerUPN.ps1].

De gewenste koppelmethode wordt aangeduid met één van de volgende variabelen. 

** `medewerker_id=loginaccount` : Koppel Id aan Magister loginaccount. Id bevat geen domeinsuffix. SDS vult Id aan met een domeinsuffix. 

** `medewerker_id=code` : Koppel Id aan Magister code. Id bevat geen domeinsuffix. School Data Sync (SDS) vult Id aan met een domeinsuffix.

** `medewerker_id=csv_upn` : Koppel Id aan UserPrincipalName van de gebruiker in een extern CSV-bestand waarvan employeeId overeenkomt met Magister stamnummer. Zie sectie Medewerker-UPN-CSV voor een beschrijving van dit bestand. Id bevat de domeinsuffix.

** `leerling_id=loginaccount` : koppel Id aan Magister loginaccount. Id bevat geen domeinsuffix. SDS vult Id aan met een domeinsuffix.

** `leerling_id=email` : Koppel ID aan Magister email. Id bevat een domeinsuffix. De leerlingen worden uniek geidentificeerd met het "email" veld in de Magister leerlingkaart. Het is de verantwoordelijkheid van de school om ervoor te zorgen dat het email-veld van leerlingen is ingevuld met de overeenkomstige userPrincipalName van de leerling in Azure AD / Microsoft 365. 

== Bestanden en mappen

=== Configuratiebestand
Dit bestand heet bij verstek `Import-Magister.ini` voor het importscript of `Export-SchoolDataSync.ps1` voor het exportscript en staat in dezelfde map als het script. Het bevat configuratievariabelen die de werking van TeamSync beinvloeden. Een andere bestandsnaam kan worden aangegeven door middel van de  <<Parameter Inifile>>. Configuratievariabelen worden behandeld in hoofdstuk <<Configuratie>>.

=== Importfiltermap
In deze map worden <<Filters>> geplaatst ten behoeve van het importscript.

=== Importkladmap
Het importscript plaatst hier tijdelijke bestanden, die kunnen worden gebruikt om de goede werking te controleren van de Magister webservice.

=== Importdatamap
In deze map plaatst het importscript de uit Magister opgehaalde gegevens over leerlingen docenten. Het exportscript leest deze in en bewerkt ze verder. 

* `magister_leer.clixml`
* `magister_docent.clixml`
* `magister_vak.clixml`

Bestanden met de extensie ".clixml" zijn bestanden  in een XML-formaat die door PowerShell kunnen worden weergegeven met het volgende commando:
[source,powershell]
----
Import-CliXML -Path $clixmlfile | Out-GridView -Wait
----

=== Exportfiltermap
In deze map worden <<Filters>> geplaatst ten behoeve van het exportscript.

=== Exportkladmap
Het exportscript plaatst hier tijdelijke bestanden, die kunnen worden gebruikt om de goede werking te controleren.

=== Exportdatamap
Het exportscript maakt in deze map volgens de specificaties van SDS de volgende bestanden aan. 

* `School.csv`
* `Section.csv`
* `Student.csv`
* `StudentEnrollment.csv`
* `Teacher.csv`
* `TeacherRoster.csv`

=== Medewerker_UPN.CSV
Dit wordt ingelezen door importscript uit de importfiltermap. Indien de koppelmethode gebruik maakt van een CSV-bestand (configuratieparameter "medewerker_id=csv_upn"), dan moet in de Importfiltermap een CSV-bestand worden aangeleverd worden. 
De naam van dit bestand is `Medewerker_UPN.csv`. De inhoud van dit bestand bestaat uit een kopregel en één of meer gegevensregels. De kopregel bevat "employeeId,UserPrincipalName". Voor elke medewerker in Magister is er een gegevensregel. De gegevensregels bevatten elk twee gegevensvelden, gescheiden door een komma. Het eerste gegevensveld bevat het stamnummer van een medewerker. Het tweede gegevensveld bevat de overeenkomstige UserPrincipalName die de gebruiker in Microsoft 365 uniek identificeert. De velden mogen omsloten zijn door dubbele aanhalingstekens, maar dat is niet verplicht.

=== Filters
In de Importfiltermap kunnen één of meer filters worden geplaatst, die de hoeveelheid te verwerken gegevens reduceren. Er zijn een aantal filters te definieren , die zowel in `Import-Magister.ps1` als `Export-SchoolDataSync.ps1` wordt gebruikt. De volgende filters kunnen worden gedefinieerd door het overeenkomstige bestand in de Importfiltermap te definieren. 

* `excl_docent.csv` : dit bevat filters voor het uitsluiten van docenten op Id.
* `incl_docent.csv` : dit bevat filters voor het insluiten van docenten op Id.
* `excl_klas.csv` : dit bevat filters voor het uitsluiten van leerlingen op klasnaam.
* `incl_klas.csv` : dit bevat filters voor het insluiten van leerlingen op klasnaam.
* `excl_studie.csv` : dit bevat filters voor het uitsluiten van leerlingen op studie.
* `incl_studie.csv` : dit bevat filters voor het insluiten van leerlingen op studie.
* `incl_locatie.csv` : dit bevat filters voor het insluiten van leerlingen op locatie.

Deze bestanden bevatten filters, die selectief records uit de invoer filteren. Hierbij wordt gebruik gemaakt van zogenaamde regular expressions. Ze kunnen **exclusief** of uitsluitend filteren, dat wil zeggen dat overeenkomende records worden weggegooid en uitgesloten van verwerking, of ze kunnen **inclusief** of insluitend filteren, dat wil zeggen dat alleen de overeenkomende records verder worden verwerkt.

Het gebruik van deze filterbestanden is optioneel. Als ze bestaan, worden ze ingelezen en gebruikt. Als ze niet bestaan, wordt er niet gefilterd. Indien gebruikt, dan kan elk van deze bestand een of meer filters bevatten, elk op een eigen regel, die worden toegepast met behulp van de match-operator voor het filteren van de leerlingen of docenten. Elke filter matcht een deel van de invoer. Wildcards zijn niet nodig. Alle tekens met een speciale betekenis voor de match-operator zijn hierbij toegelaten. Plaats geen lege regels in het filterbestand.

Speciale betekenis hebben:

* `^` matcht het begin van een zoekterm 
* `$` matcht het eind van een zoekterm
* '\' is een escape-teken voor tekens die een speciale betekenis voor regex hebben.

Zie voor meer uitleg over de "regex"-functie https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_regular_expressions?view=powershell-7[about_Regular_Expressions]

==== Voorbeelden van filters
Voorbeeld : We willen de VAVO-leerlingen niet verwerken; alle studies die eindigen op VAVO moeten worden uitgesloten.

Het bestand data_in\excl_studie.csv wordt aangemaakt en bevat: 
```
VAVO$
```

Voorbeeld : We willen de leerlingen van Mavo, Havo, Vwo en de brugklassen verwerken; alle leerlingen in een studie die begint met B,M,H of V moeten worden verwerkt. 

Het bestand data_in\incl_studie.csv wordt aangemaakt en bevat:
```
^M
^H
^V
^B
```

Voorbeeld : we willen alleen 4 en 5 Havo en verwerken; alle leerlingen in de klas die begint met '4H' of '5H' moeten worden verwerkt. 

Het bestand data_in\incl_klas.csv wordt aangemaakt en bevat:
```
^5H
^4H
```

voorbeeld: we willen alleen docenten wiens id niet begint met '_' of eindigt op '*'. 
Het bestand data_in\excl_docent.csv bevat:
```
^_
\*$
```

== Configuratie

Het configuratiebestand definieert een aantal parameters (anders gezegd: configuratievariabelen), die nodig zijn voor de correct werking van TeamSync.

De parameters in het configuratiebestand worden gespecificeerd als een naam-waarde-paar en hebben de volgende vorm:

```
<naam>=<waarde>
```

Aanhalingstekens zijn toegestaan maar niet nodig. Spaties in het waarde-deel zijn toegestaan. Commentaarregels zijn toegestaan, door de regel te beginnen met '#'.

IMPORTANT:  Backslashes worden opgevat als escape-karakters. Om backslashes in paden op te geven, escape deze met een extra backslash. Bijvoorbeeld: `Importfiltermap=Submap1\\Submap2\\Submap3`

=== Configuratievariabelen voor importscript
De volgende parameters kunnen worden gedefinieerd.

[square]
* `Importfiltermap=waarde` : pad naar invoermap relatief t.o.v. scriptpad
* `Importkladmap=waarde` : pad naar kladmap relatief t.o.v. scriptpad
* `Importdatamap=waarde` : pad naar uitvoermap relatief t.o.v. scriptpad
* `magisterUser=waarde` : webservice-gebruikersnaam
* `magisterPassword=waarde` : webservice-wachtwoord
* `magisterUrl=waarde` : webservice-URL
* `handhaafJPTMedewerkerCodeIsLogin=waarde` : filtert dubbele identiteiten weg voor Code<>Login
* `medewerker_id=waarde` : koppelmethode voor medewerkers
* `leerling_id=waarde` : koppelmethode voor leerlingen

=== Configuratievariabelen voor exportscript
* `Importdatamap=waarde` : pad naar importdatamap relatief t.o.v. scriptpad
* `Exportfiltermap=waarde` : pad naar exportfiltermap relatief t.o.v. scriptpad
* `Exportkladmap=waarde` : pad naar exportkladmap relatief t.o.v. scriptpad
* `Exportdatamap=waarde` : pad naar exportdatamap relatief t.o.v. scriptpad
* `brin=waarde` : BRIN-nummer van de school
* `schoolnaam=waarde` : naam van de school in SDS
* `teamid_prefix=waarde` : prefix voor team-ids in SDS
* `teamnaam_prefix=waarde` : prefix voor teamnamen in SDS
* `teamnaam_suffix=waarde` : suffix voor teamnamen in SDS
* `maakklassenteams=waarde` : schakelaar voor aanmaken van een team voor iedere (stam)klas

==== Brin
Dit is het BRIN-nummer van de school. Vraag je schooladminstratie of directie hiervoor. Deze parameter is verplicht. 

==== Schoolnaam 
Dit is de schoolnaam zoals die in SDS moet zijn gedefinieerd. Deze parameter is verplicht. 

==== MagisterUser, MagisterPassword, MagisterUrl 
Deze parameters zijn verplicht. Deze gegevens zijn vereist om toegang te krijgen tot de Medius Webservices. De LAS-beheerder maakt een gebruiker aan in de Webservice gebruikerslijst in Magister. De gebruikersnaam en wachtwoord moeten worden gegeven in `MagisterUser` en `MagisterPassword`. Deze gebruiker heeft toegangsrechten nodig tot de *_ADfuncties_* in de Medius Webservices. De MagisterUrl is de URL waar de webservices worden aangeboden. Dit bestaat uit de schoolspecifieke URL voor  Schoolwerkplek met daarachter poort en padaanduiding _:8800/doc_ . De hele URL ziet er uit als `https://schooldomein.swp.nl:8800/doc`.

==== Teamid_prefix
Deze tekst wordt toegevoegd aan het begin van de ID van team. Dit wordt deel van de unieke ID die elk team uniek identificeert in Microsoft 365. Een nuttige prefix identificeert zowel de school als het schooljaar en is bijvoorbeeld "JPT 1920". Spaties in de naam worden omgezet in underscores ten behoeve van het bepalen van de ObjectID. Deze parameter is verplicht. 

==== Teamnaam_prefix
Deze tekst wordt toegevoegd aan het begin van de weergavenaam van elk team en wordt zichtbaar in de teamlijst van alle deelnemers.

==== Teamnaam_suffix
Deze tekst wordt toegevoegd aan het eind van de weergavenaam van elk team en wordt zichtbaar in de teamlijst van alle deelnemers.

==== Importfiltermap
Dit specifieert de naam van de Importfiltermap, relatief ten opzichte van de locatie van het script. Bij verstek is de naam `ImportFilter`. 

==== Importkladmap
Dit specificeert de mapnaam van de Importkladmap relatief ten opzichte van de locatie van het script. Bij verstek is de naam `ImportKlad`.

==== Importdatamap
Dit specificeert de mapnaam van de Importdatamap relatief ten opzichte van de locatie van het script. Bij verstek is de naam `ImportData`.

==== Exportfiltermap
Dit specifieert de naam van de Importfiltermap, relatief ten opzichte van de locatie van het script. Bij verstek is de naam `ExportFilter`. 

==== Exportkladmap
Dit specificeert de mapnaam van de Importkladmap relatief ten opzichte van de locatie van het script. Bij verstek is de naam `ExportKlad`.

==== Exportdatamap
Dit specificeert de mapnaam van de Importdatamap relatief ten opzichte van de locatie van het script. Bij verstek is de naam `ExportData`.

==== handhaafJPTMedewerkerCodeIsLogin 
Gebruik `handhaafJPTMedewerkerCodeIsLogin=1`. Bij verstek geldt `handhaafJPTMedewerkerCodeIsLogin=0` . Deze instelling dient om uitsluitend medewerkers te verwerken waarbij Magister->Code gelijk is aan Magister->loginaccount.naam. Dit filter wordt in een speciaal geval voor JPT toegepast om dubbele identiteiten weg te filteren. 

==== medewerker_id
Deze parameter duidt aan hoe identiteiten van medewerkers in Azure AD worden gekoppeld aan Magister. Deze parameter is verplicht. Toegestane waarden zijn 
`code`, `loginaccount`, `ad_upn`, `csv_upn`
. Zie <<Identiteiten koppelen>> . 

==== leerling_id
Deze parameter duidt aan hoe identiteiten van leerlingen in Azure AD worden gekoppeld aan Magister. Deze parameter is verplicht. Toegestane waarden zijn 
`loginaccount`, `email`
. Zie <<Identiteiten koppelen>> . 

== Commandoregelparameters

=== Parameter Inifile 
Met de commandoregelparameter `-Inifile` wordt de naam van een alternatief <<Configuratie>>-bestand opgegeven. De naam is geinterpreteerd als relatief ten opzichte van de map waarin het script staat. Deze voorziening maakt het mogelijk om gegevens van verscheidene instanties van Magister gescheiden te verwerken. 

Een voorbeeld : 

 <scriptnaam> -Inifile <bestandsnaam> 

waarbij `<bestandsnaam>` de naam is van een configuratiebestand. De commandoregelparameter heeft een aantal aliassen. Deze zijn `Inifilename`,`Inibestandsnaam`,`Config`,`Configfile`,`Configuratiebestand`. Een alternatief configuratiebestand kan dus ook worden opgegeven met bijvoorbeeld: 

 <scriptnaam> -Config <bestandsnaam> 

==== Voorbeeld
Met het volgende CMD commandoscript kan het configuratiebestand 'Team-JPT.ini' worden gebruikt om script 1 en 2 uit te voeren, wanneer deze in dezelfde map als dit commandoscript staan. 

```
@echo off
Powershell.exe -NoProfile -NoLogo -ExecutionPolicy Bypass -File "%~dp0Import-Magister.ps1" -Inifile "Team-JPT.ini"
Powershell.exe -NoProfile -NoLogo -ExecutionPolicy Bypass -File "%~dp0Export-SchoolDataSync.ps1" -IniFile "Team-JPT.ini"
```

== Tips en trucs

=== Run de scripts

Vanaf de PowerShell prompt gebruikmaken van verstekwaarden:
```
. .\Import-Magister.ps1
. .\Export-SchoolDataSync.ps1
```
Vanaf PowerShell prompt met parameters:
```
. .\Import-Magister.ps1 -IniFile Magister.ini
. .\Export-SchoolDataSync.ps1 -IniFile School1.ini
```

Vanaf de CMD prompt of door middel van een batchbestand:
```
@PowerShell.exe -NoProfile -NoLogo -ExecutionPolicy Bypass -File "%~dp0Import-Magister.ps1" -IniFile Magister.ini
@PowerShell.exe -NoProfile -NoLogo -ExecutionPolicy Bypass -File "%~dp0Export-SchoolDataSync.ps1" -IniFile School1.ini
```

=== Wat als het script op zijn bek gaat?

De twee scripts loggen alle schermuitvoer en foutmeldingen in een logbestand, met de naam van het script en extensie ".log". Bestudeer deze logs om te onderzoeken welke foutmeldingen zijn gegenereerd, en op welke regel dat gebeurde.

=== Controle van uitvoer

In de Importkladmap produceert TeamSync een aantal bestanden, die inzicht geven in welke teams door School Data Sync aangemaakt zouden worden en welke gegevens worden verwerkt. Deze bestanden hebben een CSV-formaat (Comma Separated Values) en kunnen met Excel worden geopend.

Script `Ophalen` genereert onder andere: 

* `leerling.csv` : CSV-bestand met platte leerlinglijst uit Magister
* `docent.csv` : CSV-bestand met platte medewerkerlijst uit Magister

Script `Transformeren` genereert onder andere:

* `teamactief.csv` : CSV-bestand met teams die als actief worden aangeduid en die in de uitvoer voor SDS voorkomen: teamid, teamnaam, docentaantal, docentnamen, leerlingaantal, leerlingnamen.
* `team0doc.csv` : CSV-bestand met Teams die als inactief zijn aangeduid omdat ze geen docent(en) bevatten.
* `team0ll.csv` : CSV-bestand met Teams die als inactief zijn aangeduid omdat ze geen leerlingen bevatten.

Ook worden enkele *.clixml bestanden aangemaakt, die met behulp van PowerShell kunnen worden ingelezen. 

=== Typische gebruikscenarios

==== Testen

Gedurende het testen is het meest  handig als `Import-Magister.ps1` gedurende een run zonder filters wordt uitgevoerd om alle gegevens op te halen uit Magister. Wanneer dit eenmaal is gebeurd, dan kan `Export-SchoolDataSync.ps1` herhaaldelijk met één of meer filters worden uitgevoerd om te kijken wat het resultaat zou worden. Dit laatste script wordt veel sneller uitgevoerd, omdat het niet steeds opnieuw de gegevens uit Magister hoeft op te halen. 

==== Een Magister, twee scholen  (UITWERKEN)

Een scenario van het soort 'Één Magister - twee scholen' kan er zo uitzien: 

* Het script `Import-Magister.ps1` wordt uitgevoerd met een aangepast configuratiebestand, zonder filters, dat alle gegevens worden opgehaald uit Magister. Dit levert snelheidswinst op. De tussenresultaten worden opgeslagen in een algemene Importkladmap.

* De tussenresultaten `mag_leer.clixml`, `mag_doc.clixml` `mag_vak.clixml` en eventueel `personeelemail.clixml` worden gekopieerd van de algemene Importkladmap naar een school-specifieke Importkladmap.
* Het script `Export-SchoolDataSync.ps1` wordt één keer uitgevoerd voor elke school met een voor één school specifiek configuratiebestand: 
** Importfiltermap, Importkladmap en Importdatamap verwijzen naar een school-specifieke map 
** de schoolspecifieke Importfiltermap bevat school-specifieke filters, bijvoorbeeld voor locatie. 
** `teamid_prefix` verschilt per school.

Door de schoolspecifieke filters worden alleen de leerlingen verwerkt die voor een school interessant zijn. Dit verhoogt de verwerkingssnelheid. 

Dit scenario wordt compleet met een synchronisatieprofiel voor elke school in School Data Sync. De uitvoerbestanden worden geupload naar het respectievelijke synchronisatieprofiel.

== Handige links

* https://sds.microsoft.com/[Microsoft School Data Sync]
* https://github.com/DwayneSelsig/Somtoday2MicrosoftSchoolDataSync[DwayneSelsig/Somtoday2MicrosoftSchoolDataSync]
